### ISSUE TITLE
The potential for Sound speed estimation and Phase aberration correction ?

### ISSUE THREAD

**Issue by Yuxin-Zhang-Jasmine** [nbottenus/REFoCUS#1]
I'm curious about why REFoCUS can help **Sound speed estimation** and **Phase aberration correction** ...(。≖ˇェˇ≖｡)

I'm not expert at Sound speed estimation and Phase aberration correction but I know that these two are very important for the quality of the medical ultrasound image. REFoCUS is not hard to understand, and could be more attractive if its relation with Sound speed estimation/Phase aberration correction is more clear.  :)

**Comment by rehmanali1994** [comment]
REFoCUS can recover the single element transmission information from the transmit sequence. This helps by allowing us to correct for phase aberrations on both transmit and receive by applying those corrections on an element-wise basis. The single element transmit also has a broad profile that allows us to perform sound speed tomography using measured phase aberrations.
